-- Fantasy Football Database Schema for BouMob
-- Run this SQL in your Supabase SQL Editor

-- 1. Create base tables if they don't exist

-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  username text NULL,
  team_name text NULL,
  avatar_url text NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create player table
CREATE TABLE IF NOT EXISTS public.player (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  first_name text NULL,
  last_name text NULL,
  birthdate date NULL,
  nationality text NULL,
  city text NULL,
  photo_url text NULL,
  height smallint NULL,
  is_right_foot boolean NOT NULL DEFAULT true,
  price real NULL,
  CONSTRAINT player_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create player_match_stats table
CREATE TABLE IF NOT EXISTS public.player_match_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  player_id bigint NULL,
  played boolean NULL,
  goals smallint NULL,
  assists smallint NULL,
  clean_sheet boolean NULL,
  was_goalkeeper boolean NULL,
  CONSTRAINT player_match_stats_pkey PRIMARY KEY (id),
  CONSTRAINT player_match_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES player (id) ON UPDATE CASCADE
) TABLESPACE pg_default;

-- 2. Update existing profiles table to add auth_user_id and is_admin
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS auth_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false;

-- Add unique constraint on auth_user_id
CREATE UNIQUE INDEX IF NOT EXISTS profiles_auth_user_id_key ON public.profiles(auth_user_id);

-- 2. Update existing player table to add position
ALTER TABLE public.player
ADD COLUMN IF NOT EXISTS position text;

-- 4. Update existing player_match_stats to add gameweek_id and yellow/red card columns
ALTER TABLE public.player_match_stats
ADD COLUMN IF NOT EXISTS gameweek_id bigint;

-- 4. Create gameweeks table
CREATE TABLE IF NOT EXISTS public.gameweeks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  round_number smallint NOT NULL,
  round_name text NOT NULL,
  match_date date NOT NULL,
  deadline_at timestamp with time zone NOT NULL,
  is_completed boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gameweeks_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Add index on is_completed for faster queries
CREATE INDEX IF NOT EXISTS gameweeks_is_completed_idx ON public.gameweeks(is_completed);

-- 6. Create fantasy_picks table
CREATE TABLE IF NOT EXISTS public.fantasy_picks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  profile_id bigint NOT NULL,
  gameweek_id bigint NOT NULL,
  player_1_id bigint NOT NULL,
  player_2_id bigint NOT NULL,
  player_3_id bigint NOT NULL,
  player_4_id bigint NOT NULL,
  captain_player_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fantasy_picks_pkey PRIMARY KEY (id),
  CONSTRAINT fantasy_picks_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_picks_gameweek_id_fkey FOREIGN KEY (gameweek_id) REFERENCES gameweeks(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_picks_player_1_id_fkey FOREIGN KEY (player_1_id) REFERENCES player(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_picks_player_2_id_fkey FOREIGN KEY (player_2_id) REFERENCES player(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_picks_player_3_id_fkey FOREIGN KEY (player_3_id) REFERENCES player(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_picks_player_4_id_fkey FOREIGN KEY (player_4_id) REFERENCES player(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_picks_captain_player_id_fkey FOREIGN KEY (captain_player_id) REFERENCES player(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_picks_unique_profile_gameweek UNIQUE (profile_id, gameweek_id)
) TABLESPACE pg_default;

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS fantasy_picks_profile_id_idx ON public.fantasy_picks(profile_id);
CREATE INDEX IF NOT EXISTS fantasy_picks_gameweek_id_idx ON public.fantasy_picks(gameweek_id);

-- 7. Create fantasy_scores table
CREATE TABLE IF NOT EXISTS public.fantasy_scores (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  profile_id bigint NOT NULL,
  gameweek_id bigint NOT NULL,
  player_1_points smallint DEFAULT 0,
  player_2_points smallint DEFAULT 0,
  player_3_points smallint DEFAULT 0,
  player_4_points smallint DEFAULT 0,
  captain_bonus smallint DEFAULT 0,
  total_points smallint DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fantasy_scores_pkey PRIMARY KEY (id),
  CONSTRAINT fantasy_scores_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_scores_gameweek_id_fkey FOREIGN KEY (gameweek_id) REFERENCES gameweeks(id) ON DELETE CASCADE,
  CONSTRAINT fantasy_scores_unique_profile_gameweek UNIQUE (profile_id, gameweek_id)
) TABLESPACE pg_default;

-- Add indexes for leaderboard queries
CREATE INDEX IF NOT EXISTS fantasy_scores_profile_id_idx ON public.fantasy_scores(profile_id);
CREATE INDEX IF NOT EXISTS fantasy_scores_gameweek_id_idx ON public.fantasy_scores(gameweek_id);
CREATE INDEX IF NOT EXISTS fantasy_scores_total_points_idx ON public.fantasy_scores(total_points DESC);

-- Add foreign key to player_match_stats after gameweeks table is created
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'player_match_stats_gameweek_id_fkey'
  ) THEN
    ALTER TABLE public.player_match_stats
    ADD CONSTRAINT player_match_stats_gameweek_id_fkey
    FOREIGN KEY (gameweek_id) REFERENCES gameweeks(id) ON DELETE CASCADE;
  END IF;
END $$;

-- 8. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_match_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gameweeks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fantasy_picks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fantasy_scores ENABLE ROW LEVEL SECURITY;

-- 9. Create RLS Policies

-- Profiles: Users can read all profiles, update only their own
DROP POLICY IF EXISTS "Profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Profiles are viewable by everyone" ON public.profiles
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = auth_user_id);

-- Players: Everyone can read, only admins can modify
DROP POLICY IF EXISTS "Players are viewable by everyone" ON public.player;
CREATE POLICY "Players are viewable by everyone" ON public.player
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can insert players" ON public.player;
CREATE POLICY "Admins can insert players" ON public.player
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

DROP POLICY IF EXISTS "Admins can update players" ON public.player;
CREATE POLICY "Admins can update players" ON public.player
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

DROP POLICY IF EXISTS "Admins can delete players" ON public.player;
CREATE POLICY "Admins can delete players" ON public.player
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

-- Gameweeks: Everyone can read, only admins can modify
DROP POLICY IF EXISTS "Gameweeks are viewable by everyone" ON public.gameweeks;
CREATE POLICY "Gameweeks are viewable by everyone" ON public.gameweeks
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage gameweeks" ON public.gameweeks;
CREATE POLICY "Admins can manage gameweeks" ON public.gameweeks
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

-- Fantasy Picks: Users can read all, insert/update only their own before deadline
DROP POLICY IF EXISTS "Fantasy picks are viewable by everyone" ON public.fantasy_picks;
CREATE POLICY "Fantasy picks are viewable by everyone" ON public.fantasy_picks
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert own picks before deadline" ON public.fantasy_picks;
CREATE POLICY "Users can insert own picks before deadline" ON public.fantasy_picks
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = profile_id AND auth_user_id = auth.uid()
    )
    AND EXISTS (
      SELECT 1 FROM public.gameweeks
      WHERE id = gameweek_id AND deadline_at > now()
    )
  );

DROP POLICY IF EXISTS "Users can update own picks before deadline" ON public.fantasy_picks;
CREATE POLICY "Users can update own picks before deadline" ON public.fantasy_picks
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = profile_id AND auth_user_id = auth.uid()
    )
    AND EXISTS (
      SELECT 1 FROM public.gameweeks
      WHERE id = gameweek_id AND deadline_at > now()
    )
  );

-- Fantasy Scores: Everyone can read, only system/admins can write
DROP POLICY IF EXISTS "Fantasy scores are viewable by everyone" ON public.fantasy_scores;
CREATE POLICY "Fantasy scores are viewable by everyone" ON public.fantasy_scores
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage fantasy scores" ON public.fantasy_scores;
CREATE POLICY "Admins can manage fantasy scores" ON public.fantasy_scores
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

-- Player Match Stats: Everyone can read, only admins can modify
DROP POLICY IF EXISTS "Player match stats are viewable by everyone" ON public.player_match_stats;
CREATE POLICY "Player match stats are viewable by everyone" ON public.player_match_stats
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage player match stats" ON public.player_match_stats;
CREATE POLICY "Admins can manage player match stats" ON public.player_match_stats
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

-- 10. Create storage bucket for player photos
INSERT INTO storage.buckets (id, name, public)
VALUES ('player-photos', 'player-photos', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policy: Everyone can read, admins can upload
DROP POLICY IF EXISTS "Player photos are publicly accessible" ON storage.objects;
CREATE POLICY "Player photos are publicly accessible" ON storage.objects
  FOR SELECT USING (bucket_id = 'player-photos');

DROP POLICY IF EXISTS "Admins can upload player photos" ON storage.objects;
CREATE POLICY "Admins can upload player photos" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'player-photos'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

DROP POLICY IF EXISTS "Admins can update player photos" ON storage.objects;
CREATE POLICY "Admins can update player photos" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'player-photos'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

DROP POLICY IF EXISTS "Admins can delete player photos" ON storage.objects;
CREATE POLICY "Admins can delete player photos" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'player-photos'
    AND EXISTS (
      SELECT 1 FROM public.profiles
      WHERE auth_user_id = auth.uid() AND is_admin = true
    )
  );

-- 11. Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add trigger to fantasy_scores
DROP TRIGGER IF EXISTS update_fantasy_scores_updated_at ON public.fantasy_scores;
CREATE TRIGGER update_fantasy_scores_updated_at
  BEFORE UPDATE ON public.fantasy_scores
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- 12. Create function to auto-create profile when user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (auth_user_id, username, team_name)
  VALUES (NEW.id, NEW.email, NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Add trigger to automatically create profile on signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- Done! Your fantasy football database is ready.
-- Next steps:
-- 1. Run this SQL in your Supabase SQL Editor
-- 2. Create your first admin user and set is_admin = true in the profiles table
-- 3. Add your 15 players to the player table with prices and positions
