import type { Standing } from "../types/Standing";

// This data is based on the provided screenshot for local development.
export const fakeStandingsData: Partial<Standing>[] = [
  {
    position: 1,
    orgId: 1011569,
    orgName: "Arsenal",
    matches: 14,
    victories: 11,
    draws: 1,
    losses: 2,
    totalGoalsFormatted: "89 - 48",
    goalDifference: 41,
    totalPoints: 34,
  },
  {
    position: 2,
    orgId: 1009858,
    orgName: "Barcelona",
    matches: 15,
    victories: 10,
    draws: 3,
    losses: 2,
    totalGoalsFormatted: "72 - 47",
    goalDifference: 25,
    totalPoints: 33,
  },
  {
    position: 3,
    orgId: 1009856,
    orgName: "Juventus",
    matches: 15,
    victories: 9,
    draws: 1,
    losses: 5,
    totalGoalsFormatted: "68 - 46",
    goalDifference: 22,
    totalPoints: 28,
  },
  {
    position: 4,
    orgId: 913462,
    orgName: "Bayern Munich",
    matches: 14,
    victories: 8,
    draws: 2,
    losses: 4,
    totalGoalsFormatted: "56 - 41",
    goalDifference: 15,
    totalPoints: 26,
  },
  {
    position: 5,
    orgId: 995429,
    orgName: "Paris Saint-Germain",
    matches: 15,
    victories: 6,
    draws: 1,
    losses: 8,
    totalGoalsFormatted: "60 - 76",
    goalDifference: -16,
    totalPoints: 19,
  },
  {
    position: 6,
    orgId: 177642,
    orgName: "Manchester United",
    matches: 15,
    victories: 5,
    draws: 2,
    losses: 8,
    totalGoalsFormatted: "51 - 60",
    goalDifference: -9,
    totalPoints: 17,
  },
  {
    position: 7,
    orgId: 716906,
    orgName: "Real Madrid",
    matches: 15,
    victories: 4,
    draws: 3,
    losses: 8,
    totalGoalsFormatted: "49 - 70",
    goalDifference: -21,
    totalPoints: 15,
  },
  {
    position: 8,
    orgId: 995679,
    orgName: "Liverpool",
    matches: 16,
    victories: 4,
    draws: 3,
    losses: 9,
    totalGoalsFormatted: "56 - 90",
    goalDifference: -34,
    totalPoints: 15,
  },
  {
    position: 9,
    orgId: 1000302,
    orgName: "Chelsea",
    matches: 15,
    victories: 2,
    draws: 0,
    losses: 13,
    totalGoalsFormatted: "63 - 86",
    goalDifference: -23,
    totalPoints: 6,
  },
];
